### PR TITLE
Sync

### PR DESCRIPTION
**Pull request by musicformellons**

### CODE REVIEW

**Comment by nemesisdesign** [comment]
excuse me, what does this mean?

**Comment by musicformellons** [comment]
​Hi Federico,

Sorry about this... I am new to git and must have messed up. Can you delete
it?

Sorry for the trouble caused.

Kind regards ​

2015-01-26 11:30 GMT+01:00 Federico Capoano <notifications@github.com>:

**Comment by nemesisdesign** [comment]
No problem.

Do you intend to sell a modified version of this software?
If yes, be sure to comply with the GPL v3 license, pay attention on the section where it states *+5. Conveying Modified Source Versions**:

**5. Conveying Modified Source Versions.**
You may convey a work based on the Program, or the modifications to produce it from the Program, in the form of source code under the terms of section 4, provided that you also meet all of these conditions:

**a)** The work must carry prominent notices stating that you modified it, and giving a relevant date.
**b)** The work must carry prominent notices stating that it is released under this License and any conditions added under section 7. This requirement modifies the requirement in section 4 to “keep intact all notices”.
**c)** You must license the entire work, as a whole, under this License to anyone who comes into possession of a copy. This License will therefore apply, along with any applicable section 7 additional terms, to the whole of the work, and all its parts, regardless of how they are packaged. This License gives no permission to license the work in any other way, but it does not invalidate such permission if you have separately received it.
**d)** If the work has interactive user interfaces, each must display Appropriate Legal Notices; however, if the Program has interactive interfaces that do not display Appropriate Legal Notices, your work need not make them do so.
A compilation of a covered work with other separate and independent works, which are not by their nature extensions of the covered work, and which are not combined with it such as to form a larger program, in or on a volume of a storage or distribution medium, is called an “aggregate” if the compilation and its resulting copyright are not used to limit the access or legal rights of the compilation's users beyond what the individual works permit. Inclusion of a covered work in an aggregate does not cause this License to apply to the other parts of the aggregate.

http://www.gnu.org/copyleft/gpl.html

Thank you
Federico

**Comment by musicformellons** [comment]
I admire and appreciate your work very much. I do not intend to sell the
code, but might be using it in a project. I did read the GPL v3 requirement
and am aware of the implications, but thanks for your reminder. I am a
starting programmer so still stumbling from time to time.

I have a UX feature that I think could be improved upon: When folding out
the taskbar (from the rightside bottom corner) the map shifts to the left
(to make room for the taskbar). It would be better/ more natural when the
map does not move (the taskbare then folds on top of the map).

I think I am still too lousy a programmer to contribute to the project but
if I could assist in any way please let me know!


2015-01-26 12:04 GMT+01:00 Federico Capoano <notifications@github.com>:

**Comment by nemesisdesign** [comment]
Thanks for the feedback Ray.

Yes there is something you can do to help. You could subscribe to the mailing list and send feedback there, either if you have an idea like the one you just wrote, or when we ask feedback for new features or changes we just implemented.
Also, if you find any passage in the documentation that was not clear enough, it would be useful to know.

Here's the link: http://ml.ninux.org/mailman/listinfo/nodeshot 
And the archives: http://ml.ninux.org/pipermail/nodeshot/

**Comment by musicformellons** [comment]
Ok, I will!

2015-01-26 13:26 GMT+01:00 Federico Capoano <notifications@github.com>:

**Pull request closed without merging**
