### PR TITLE
Addition to email docs

### PR DESCRIPTION
**Pull request by musicformellons**
Is this ok?

### CODE REVIEW

**Comment by nemesisdesign** [comment]
Yes, thank you!

Two suggestions for the next time:
 * avoid sending merge commit by starting out with a clean clone from github
 * avoid adding too any blank lines at the end of the file

**Comment by musicformellons** [comment]
ok, but:

   - avoid sending merge commit by starting out with a clean clone from
   github

so how should i do it then?

2015-04-18 9:58 GMT+02:00 Federico Capoano <notifications@github.com>:

**Comment by nemesisdesign** [comment]
ensure your fork is clean, clone your fork from github on your local env, edit the file, commit, push to your fork, send pull request.

**Comment by musicformellons** [comment]
isn't that exactly what I did?

2015-04-18 10:07 GMT+02:00 Federico Capoano <notifications@github.com>:

**Comment by nemesisdesign** [comment]
It seems the fork wasn't clean, because this merge commit was added: https://github.com/ninuxorg/nodeshot/commit/f9336815b65cbc36ce5c7c3a01b079c1f4fef1f2

Merge commits are avoidable and confusing, also because it references pull request #1 which is not relevant to this ticket!

**Comment by musicformellons** [comment]
git is still a bit of a puzzle to me I'm afraid. I will try to do as you
suggest next time... No guarantuees... :-)

2015-04-18 10:14 GMT+02:00 Federico Capoano <notifications@github.com>:

**Comment by nemesisdesign** [comment]
Try reading something about git, it will surely enable you to do powerful things :-)
Fed

**Pull request merged**
